services:
  # The Flask web application service.
  web:
    # Build the Docker image from the Dockerfile in the current directory.
    build: .
    container_name: petcare-web
    ports:
      - "5000:5000"
    # UPDATED: Reverted to using 'volumes' for live code syncing,
    # which is compatible with all versions of Docker Compose.
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_started
    restart: unless-stopped

  # The MongoDB database service.
  mongo:
    image: mongo:latest
    container_name: petcare-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
