services:
  # The Flask web application service.
  web:
    # UPDATED: Instead of building, pull the pre-built image from Docker Hub.
    container_name: petcare-web
    ports:
      - "5000:5000"
    # The volume for code syncing is removed for deployment.
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_started
    restart: unless-stopped

  # The MongoDB database service.
  mongo:
    image: mongo:latest
    container_name: petcare-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
