version: "3.8"

services:
  # The Flask web application service
  web:
    image: shaikmunawar/petcare-web:1.0
    container_name: petcare-web
    ports:
      - "80:5000"
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_started
    restart: always

  # The MongoDB database service
  mongo:
    image: mongo:latest
    container_name: petcare-mongo
    ports:
      - "127.0.0.1:27017:27017"  # Binds only to EC2 localhost (not public)
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
